#include "ability.h"
#include "eventHandlers.h"
//stub function, autogenerated
void FlashAbilityColor() {
 
}

//stub function, autogenerated
void SavePause() {
 
}

//stub function, autogenerated
void SaveAbility() {
 
}

//stub function, autogenerated
void FlashWrong() {
 
}

//stub function, autogenerated
void StartAbility() {
 
}