#include "eventHandlers.h"
//stub function, autogenerated
void FlashAbilityColor() {
 
}

//stub function, autogenerated
void FlashWrong() {
 
}

//stub function, autogenerated
void StartAbility() {
 
}

void MonsterVibro() {

}

void ClearPill() {

}

void Flash(Color color) {

}

void StartTramsmitForPath() {

}

void SetColor(Color color) {

}


void SaveState(unsigned int State) {

}

void VibroRadiation() {

}