#include "eventHandlers.h"
//stub function, autogenerated
void FlashAbilityColor() {
 
}

//stub function, autogenerated
void SavePause() {
 
}

//stub function, autogenerated
void SaveAbility() {
 
}

//stub function, autogenerated
void FlashWrong() {
 
}

//stub function, autogenerated
void StartAbility() {
 
}

void MonsterVibro() {

}

void SetHealth(unsigned int Health) {

}

void ClearPill() {

}

void SaveGodTimer() {

}

void SaveAbility(unsigned int Ability) {

}

void Flash(Color color) {

};